editor: nvim
viewer: zathura
terminal: xfce4-terminal
notes_dir: ~/Documents/notes
root: ~/Documents/notes/Grade-10/semester-2
current_course: ~/Documents/notes/current-course
source_lessons_location: ~/Documents/notes/current-course/source-lessons.tex
unit_info_name: unit-info.tex
new_chap: False
home: ~/
user: hashem
regex: r'\\lesson\{(.*?)\}\{(.*?)\}\{(.*?)\}\{(.*?)\}'
LESSON_RANGE_NUMBER: 1000

rofi_options:
  - -lines
  - 5
  - -markup-rows
  - -kb-row-down
  - Down
  - -kb-custom-1
  - Ctrl+n

tex_types:
  - .tex
  - .latex

discourage_folders:
  - images
  - assignments
  - figures
  - projects
  - .git
  - media
  - current-course
