#!/usr/bin/env bash

export DOCUMENTS="$HOME/Documents"
export NOTES_DIR="$DOCUMENTS/school-notes"
export CURRENT_COURSE="$NOTES_DIR/current-course"
export ASSIGNMENTS_DIR="$CURRENT_COURSE/assignments"

export GRADED_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/graded-assignments"
export MY_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/my-assignments"
export ONLINE_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/online-assignments"

export DIR="$HOME/.config/lesson-manager"
export SRC="$HOME/.config/lesson-manager/config.yaml"

function msg() {
  local text="$1"
  local div_width="80"

  printf "%${div_width}s\n" ' ' | tr ' ' -
  printf "%s\n" "$text"
}

if [[ ! -d "$DIR" ]]; then
  msg "Creating folder to store config.yaml"

  mkdir "$DIR"
fi

if [[ -e "$SRC" ]]; then
  msg "Backing up config.yaml"

  mv "$SRC" "$SRC.back"
fi

msg "Adding configuration template"

echo "calendar_id: \"primary\"
base_url: \"URL\"

code_dir: \"$DOCUMENTS/school-setup\"
editor: \"$HOME/.local/bin/dvim\"
viewer: \"sioyek\"
terminal: \"xfce4-terminal\"

notes_dir: \"$DOCUMENTS/school-notes\"
root: \"$NOTES_DIR/College/Year-2/semester-1\"
current_course: \"$NOTES_DIR/current-course\"
master_file: \"$CURRENT_COURSE/master.tex\"
source_lessons_location: \"$CURRENT_COURSE/source-lectures.tex\"

assignments_dir: \"$CURRENT_COURSE/assignments\"
graded_assignments_folder: \"$ASSIGNMENTS_DIR/graded-assignments\"
my_assignments_folder: \"$ASSIGNMENTS_DIR/my-assignments\"
online_assignments_folder: \"$ASSIGNMENTS_DIR/online-assignments\"

my_assignments_latex_folder: \"$MY_ASSIGNMENTS_DIR/latex-files\"
my_assignments_yaml_folder: \"$MY_ASSIGNMENTS_DIR/yaml-files\"
my_assignments_pdf_folder: \"$MY_ASSIGNMENTS_DIR/pdf-files\"

date_format: \"%b %d %Y %a (%H:%M:%S)\"
home: \"$HOME\"
user: \"$USER\"

rofi_options:
  - \"-lines\"
  - \"5\"
  - \"-markup-rows\"
  - \"-kb-row-down\"
  - \"Down\"
  - \"-kb-custom-1\"
  - \"Ctrl+n\"

tex_types:
  - \".tex\"
  - \".latex\"

discourage_folders:
  - \"images\"
  - \"assignments\"
  - \"figures\"
  - \"projects\"
  - \".git\"
  - \"media\"
  - \"current-course\"

folders:
  - \"assignments\"
  - \"assignments/image-files\"
  - \"assignments/latex-files\"
  - \"assignments/pdf-files\"
  - \"assignments/yaml-files\"
  - \"lectures\"
  - \"figures\"
  - \"UltiSnips\"" >> ~/.config/lesson-manager/config.yaml

msg "Successfuly got everything ready"
