#!/usr/bin/env bash

export DOCUMENTS="~/Documents"
export NOTES_DIR="$DOCUMENTS/school-notes"
export CURRENT_COURSE="$NOTES_DIR/current-course"
export ASSIGNMENTS_DIR="$CURRENT_COURSE/assignments"

export GRADED_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/graded-assignments"
export MY_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/my-assignments"
export ONLINE_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/online-assignments"

export DIR="$HOME/.config/lesson-manager"
export SRC="$HOME/.config/lesson-manager/config.yaml"

function msg() {
  local text="$1"
  local div_width="80"

  printf "%${div_width}s\n" ' ' | tr ' ' -
  printf "%s\n" "$text"
}

if [[ ! -d "$DIR" ]]; then
  msg "Creating folder to store config.yaml"

  mkdir "$DIR"
fi

if [[ -e "$SRC" ]]; then
  msg "Backing up config.yaml"

  mv "$SRC" "$SRC.back"
  rm -rf "$SRC"
fi

msg "Adding configuration template"

echo "---
calendar_id: \"primary\"
drive_folder_id: \"\"

editor: \"nvim\"
terminal: \"kitty\"
pdf_viewer: \"zathura\"

create_readme_file: true
highlight_current_course: true

notes_dir: \"$DOCUMENTS/school-notes\"
root: \"$NOTES_DIR/College/Year-2/fall\"
templates_dir: \"$NOTES_DIR/College/Year-2/fall/_files\"
current_course: \"$NOTES_DIR/current-course\"

books_dir: \"$CURRENT_COURSE/books\"
figures_dir: \"$CURRENT_COURSE/figures\"

date_format: \"%b %d %Y %a (%H:%M:%S)\"
home: \"$HOME\"
user: \"$USER\"
trash_dir: \"$XDG_DATA_HOME/lesson-manager/Year-2/fall\"

assignments_dir: \"$CURRENT_COURSE/assignments\"
assignment_folders:
  bib_folder: \"my-assignments/bibtex-files\"
  tex_folder: \"my-assignments/latex-files\"
  yaml_folder: \"my-assignments/yaml-files\"
  pdf_folder: \"my-assignments/pdf-files\"
  graded_assignment: \"graded-assignments\"
  online_assignment: \"online-assignments\"
  solution_key: \"solution-keys/pdf-files\"

exams_dir: \"$CURRENT_COURSE/exams\"
exam_solution_keys:
  pdf_folder: \"solution-keys/pdf-files\"
  tex_folder: \"solution-keys/latex-files\"
exam_review:
  practice: \"review/practice\"
  answers: \"review/answers\"

rofi_options:
  - \"-markup-rows\"
  - \"-kb-row-down\"
  - \"Down\"
  - \"-kb-custom-1\"
  - \"Ctrl+n\"
  - \"-no-fixed-num-lines\"

folders:
  - \"assignments\"
  - \"assignments/graded-assignments\"
  - \"assignments/online-assignments\"
  - \"assignments/solution-keys\"
  - \"assignments/solution-keys/pdf-files\"
  - \"assignments/solution-keys/latex-files\"
  - \"assignments/my-assignments\"
  - \"assignments/my-assignments/bibtex-files\"
  - \"assignments/my-assignments/image-files\"
  - \"assignments/my-assignments/latex-files\"
  - \"assignments/my-assignments/pdf-files\"
  - \"assignments/my-assignments/sympy-scripts\"
  - \"assignments/my-assignments/yaml-files\"
  - \"books\"
  - \"exams\"
  - \"exams/review\"
  - \"exams/review/answers\"
  - \"exams/review/practice\"
  - \"exams/solution-keys\"
  - \"exams/solution-keys/pdf-files\"
  - \"exams/solution-keys/latex-files\"
  - \"figures\"
  - \"note-guide\"
  - \"papers\"
  - \"sympy-scripts\"
  - \"UltiSnips\"

files:
  \"assignments/my-assignments/preamble.tex\": \"symlink\"
  \"assignments/my-assignments/Makefile\": \"symlink\"
  \"assignments/solution-keys/Makefile\": \"symlink\"
  \"assignments/solution-keys/preamble.tex\": \"symlink\"
  \"exams/solution-keys/preamble.tex\": \"symlink\"
  \"exams/solution-keys/Makefile\": \"symlink\"
  \"Makefile\": \"symlink\"
  \"preamble.tex\": \"symlink\"
  \"UltiSnips/tex.snippets\": \"symlink\"
  \"assignments/my-assignments/master.tex\": \"copy\"
  \"assignments/solution-keys/master.tex\": \"copy\"
  \"exams/solution-keys/master.tex\": \"copy\"
  \"intro.tex\": \"copy\"
  \"master.tex\": \"copy\"
  \"notes.md\": \"copy\"" >> "$SRC"

msg "Successfuly got everything ready"
