#!/usr/bin/env bash

export DOCUMENTS="~/Documents"
export NOTES_DIR="$DOCUMENTS/school-notes"
export CURRENT_COURSE="$NOTES_DIR/current-course"
export ASSIGNMENTS_DIR="$CURRENT_COURSE/assignments"

export GRADED_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/graded-assignments"
export MY_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/my-assignments"
export ONLINE_ASSIGNMENTS_DIR="$ASSIGNMENTS_DIR/online-assignments"

export DIR="$HOME/.config/lesson-manager"
export SRC="$HOME/.config/lesson-manager/config.yaml"

function msg() {
  local text="$1"
  local div_width="80"

  printf "%${div_width}s\n" ' ' | tr ' ' -
  printf "%s\n" "$text"
}

if [[ ! -d "$DIR" ]]; then
  msg "Creating folder to store config.yaml"

  mkdir "$DIR"
fi

if [[ -e "$SRC" ]]; then
  msg "Backing up config.yaml"

  mv "$SRC" "$SRC.back"
  rm -rf "$SRC"
fi

msg "Adding configuration template"

echo "calendar_id: \"primary\"

code_dir: \"$DOCUMENTS/school-setup\"
editor: \"nvim\"
terminal: \"kitty\"
pdf_viewer: \"zathura\"

create_readme_file: true

notes_dir: \"$DOCUMENTS/school-notes\"
root: \"$NOTES_DIR/College/Year-1/winter\"
templates_dir: \"$NOTES_DIR/College/Year-1/winter/_files\"
current_course: \"$NOTES_DIR/current-course\"

books_dir: \"$CURRENT_COURSE/books\"
figures_dir: \"$CURRENT_COURSE/books\"

assignments_dir: \"$CURRENT_COURSE/assignments\"
graded_assignments_folder: \"$ASSIGNMENTS_DIR/graded-assignments\"
my_assignments_folder: \"$ASSIGNMENTS_DIR/my-assignments\"
online_assignments_folder: \"$ASSIGNMENTS_DIR/online-assignments\"

my_assignments_image_folder: \"$MY_ASSIGNMENTS_DIR/latex-files\"
my_assignments_bibtex_folder: \"$MY_ASSIGNMENTS_DIR/bibtex-files\"
my_assignments_latex_folder: \"$MY_ASSIGNMENTS_DIR/latex-files\"
my_assignments_yaml_folder: \"$MY_ASSIGNMENTS_DIR/yaml-files\"
my_assignments_pdf_folder: \"$MY_ASSIGNMENTS_DIR/pdf-files\"

date_format: \"%b %d %Y %a (%H:%M:%S)\"
home: \"$HOME\"
user: \"$USER\"

rofi_options:
  - \"-lines\"
  - \"5\"
  - \"-markup-rows\"
  - \"-kb-row-down\"
  - \"Down\"
  - \"-kb-custom-1\"
  - \"Ctrl+n\"

folders:
  - \"assignments\"
  - \"assignments/graded-assignments\"
  - \"assignments/online-assignments\"
  - \"assignments/my-assignments\"
  - \"assignments/my-assignments/bibtex-files\"
  - \"assignments/my-assignments/image-files\"
  - \"assignments/my-assignments/latex-files\"
  - \"assignments/my-assignments/pdf-files\"
  - \"assignments/my-assignments/sympy-scripts\"
  - \"assignments/my-assignments/yaml-files\"
  - \"books\"
  - \"figures\"
  - \"papers\"
  - \"online-lecture-notes\"
  - \"sympy-scripts\"
  - \"UltiSnips\"

files:
  \"assignments/my-assignments/preamble.tex\": \"symlink\"
  \"assignments/my-assignments/Makefile\": \"symlink\"
  \"Makefile\": \"symlink\"
  \"preamble.tex\": \"symlink\"
  \"assignments/my-assignments/master.tex\": \"copy\"
  \"intro.tex\": \"copy\"
  \"master.tex\": \"copy\"
  \"notes.norg\": \"copy\"
  \"UltiSnips/tex.snippets\": \"copy\"" >> "$SRC"

msg "Successfuly got everything ready"
