calendar_id: "primary"
drive_folder_id: "drive_folder_id"

code_dir: "~/school-setup"
editor: "nvim"
terminal: "kitty"
pdf_viewer: "zathura"

create_readme_file: true
highlight_current_course: true

notes_dir: "~/school-setup/example-setup"
root: "~/school-setup/example-setup/courses"
templates_dir: "~/school-setup/template_files"
current_course: "~/school-setup/current-course"

books_dir: "~/school-setup/current-course/books"

figures_dir: "~/school-setup/current-course/figures"

assignments_dir: "~/school-setup/current-course/assignments"
graded_assignments_folder: "~/school-setup/current-course/assignments/graded-assignments"
my_assignments_folder: "~/school-setup/current-course/assignments/my-assignments"
online_assignments_folder: "~/school-setup/current-course/assignments/online-assignments"

my_assignments_image_folder: "~/school-setup/current-course/assignments/my-assignments/latex-files"
my_assignments_bibtex_folder: "~/school-setup/current-course/assignments/my-assignments/bibtex-files"
my_assignments_latex_folder: "~/school-setup/current-course/assignments/my-assignments/latex-files"
my_assignments_yaml_folder: "~/school-setup/current-course/assignments/my-assignments/yaml-files"
my_assignments_pdf_folder: "~/school-setup/current-course/assignments/my-assignments/pdf-files"

date_format: "%b %d %Y %a (%H:%M:%S)"
home: "/home/user"
user: "user"

rofi_options:
  - "-lines"
  - "5"
  - "-markup-rows"
  - "-kb-row-down"
  - "Down"
  - "-kb-custom-1"
  - "Ctrl+n"
  - "-no-fixed-num-lines"

folders:
  - "assignments"
  - "assignments/graded-assignments"
  - "assignments/online-assignments"
  - "assignments/my-assignments"
  - "assignments/my-assignments/bibtex-files"
  - "assignments/my-assignments/image-files"
  - "assignments/my-assignments/latex-files"
  - "assignments/my-assignments/pdf-files"
  - "assignments/my-assignments/sympy-scripts"
  - "assignments/my-assignments/yaml-files"
  - "books"
  - "exam-review"
  - "figures"
  - "papers"
  - "online-lecture-notes"
  - "sympy-scripts"
  - "UltiSnips"

files:
  "assignments/my-assignments/preamble.tex": "symlink"
  "assignments/my-assignments/Makefile": "symlink"
  "Makefile": "symlink"
  "preamble.tex": "symlink"
  "UltiSnips/tex.snippets": "symlink"
  "assignments/my-assignments/master.tex": "copy"
  "intro.tex": "copy"
  "master.tex": "copy"
  "notes.md": "copy"
